### ISSUE TITLE
Link to comments visible on comments page itself

### ISSUE THREAD

**Issue by patrickBerry** [sbuggay/yahn#7]
The link to view the comments for a particular article is visible when viewing said comments. Clicking the link takes the user to the page they are already on. This action counts as going to a new page, so if the link to the comments has been clicked several times then the user must go back that many pages to get back to where they started. This is surprising because I have found my self several pages deep by accident. Since the page loads immediately it's not always obvious that the user has navigated to another page (albeit the identical one). I think a simple fix may be to just not provide a link to the comments when viewing the comments.

**Comment by sbuggay** [comment]
Removed the `comments` text being a link if you are on the page it links to.
