### ISSUE TITLE
Ask links do not behave as expected

### ISSUE THREAD

**Issue by patrickBerry** [sbuggay/yahn#8]
When viewing the "ask" section/tab portion of the site, expected behavior for the articles is that clicking on the title of the article takes the user to the content page of the article. Since "ask" articles content is the comment section itself, expected behavior would be that clicking the title would take the user to the comment section. However, as it is now, clicking the title on the ask section highlights/underlines link a normal link, but does not navigate anywhere. The suggested fix is that clicking the title will take the user to the comment section.

**Comment by sbuggay** [comment]
Agreed, completed.
